import React from "react";
import { Card } from "@/components/ui/Card";

interface OtisTakeProps {
  otisTake: string;
}

const LEGAL_DISCLAIMER =
  "This report is generated by an AI system for informational purposes only and does not constitute financial, legal, or real estate advice. All analysis is based on publicly available data and estimated figures. Market conditions change rapidly, and this analysis may not reflect current conditions. Always consult licensed professionals \u2014 including a real estate agent, mortgage lender, and attorney \u2014 before making any real estate purchase decision. Otis is not liable for any losses or damages resulting from reliance on this report.";

export function OtisTake({ otisTake }: OtisTakeProps) {
  return (
    <Card>
      <div className="flex items-center gap-3 mb-4">
        <div className="flex-shrink-0 w-10 h-10 rounded-full bg-[var(--accent)] flex items-center justify-center">
          <span className="text-white font-bold text-sm">O</span>
        </div>
        <h2 className="text-lg font-semibold text-[var(--text-primary)]">
          Otis&apos;s Take
        </h2>
      </div>

      <div className="bg-[var(--bg-warm)] border border-[var(--border)] rounded-xl p-5 mb-5">
        <p className="text-[var(--text-secondary)] leading-relaxed text-base">{otisTake}</p>
      </div>

      {/* Legal disclaimer */}
      <div className="flex gap-2 p-4 bg-[var(--bg-page)] rounded-lg border border-[var(--border)]">
        <svg
          className="w-4 h-4 text-[var(--text-muted)] flex-shrink-0 mt-0.5"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
          strokeWidth={2}
          aria-hidden="true"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
          />
        </svg>
        <p className="text-xs text-[var(--text-muted)] leading-relaxed">
          {LEGAL_DISCLAIMER}
        </p>
      </div>
    </Card>
  );
}
